#!/usr/bin/env python3.5
import sys, pickle

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Ugly please remove TODO FIXME thanks lol
from tensorflow.keras.models import *
from tensorflow.keras.layers import *

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

import random
from pprint import pprint

def unpair(paired):
    A = []
    B = []
    for a, b in paired:
        A.append(a)
        B.append(b)
    return A, B

maxbits = 32
sequence_length = 1

to_binary_list  = lambda n : list(map(int, bin(n)[2:]))
pad_binary_list = lambda l : [0] * (maxbits - len(l)) + l

def binary(n):
    return pad_binary_list(to_binary_list(n))

def run_nn_test(data, N, train_p, representation, epochs, randomize=True):
    print(len(data))
    if randomize:
        random.shuffle(data)

    if representation == 'binary':
        data = [(sum((binary(n) for n in ns), []), binary(label)) for ns, label in data]
    split = int(N*train_p)
    train_ns, train_labels = unpair(data[:split])
    test_ns, test_labels   = unpair(data[split:])

    train_ns = np.array(train_ns)
    train_labels = np.array(train_labels)
    test_ns  = np.array(test_ns)
    test_labels = np.array(test_labels)

    model = keras.Sequential([
        keras.layers.Dense(32, input_shape=((sequence_length * maxbits,) if representation == 'binary' else (1,))),
        keras.layers.Dense(32, activation=tf.nn.tanh),
        keras.layers.Dense(32, activation=tf.nn.tanh),
        keras.layers.Dense(32, activation=tf.nn.tanh),
        keras.layers.Dense(32)#, output_shape=(32,))#, activation=tf.nn.sigmoid)
    ])

    model.compile(optimizer=tf.train.AdamOptimizer(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    model.fit(train_ns, train_labels, epochs=epochs)

    print(test_ns)
    test_loss, test_acc = model.evaluate(test_ns, test_labels)
    print('Test accuracy:', test_acc)
    return model

def gen_evens(N, start=1):
    return [(2 * n, True) for n in range(start, N+1)]

def gen_odds(N, start=1):
    return [(2 * n + 1, False) for n in range(start, N+1)]

from sieve import gen_primes, gen_composites, take

functions = [lambda x : x * 2]

def main(args):
    train_p = 0.8
    predict_p = 0.8
    size = sequence_length
    representation = 'binary'
    N = offset_range = 100
    epochs = 100
    data = sum([ 
               [([f(x) for x in range(i, i+size)], 
                   f(i+size+1))
               for i in range(offset_range)]
               for f in functions], 
               [])
    pprint(data)
    model = run_nn_test(data, N, train_p, representation, epochs, randomize=True)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
