#!/usr/bin/env python3
from methods.legacy.brute_force import brute_force
from methods.legacy.heuristic   import heuristic
from methods.tree import tree
from methods.arithmetic import operators

def main():
    print(operators)
    N = 10
    function = lambda x : 2 * x + 1
    def function(x): 
        return 1 if x == 1 else x * function(x-1)
    inputs  = list(range(1, N+1))
    outputs = list(map(function, inputs))

    tree(inputs, outputs, depth=3)

if __name__ == '__main__':
    main()
