#!/usr/bin/env python3
from methods.legacy.brute_force import brute_force
from methods.legacy.heuristic   import heuristic
from methods.tree import tree
from methods.arithmetic import operators

def main():
    print(operators)
    inputs  = [1, 2, 3]
    outputs = [2, 4, 6]
    outputs = [3, 5, 7]
    outputs = [1, 2, 6]
    
    tree(inputs, outputs)

if __name__ == '__main__':
    main()
