#!/usr/bin/env python3
import sys

from math import sqrt

import numpy as np
import matplotlib.pyplot as plt

def f(i, j):
    if ((i % 2 == 0 and j % 2 != 0) or 
        (i % 2 != 0 and j % 2 == 0)):
        return 1
    else:
        return 0

__fibb_cache__ = {0 : 0, 1 : 1, 2 : 1}
def fibb(x):
    if x not in __fibb_cache__:
        __fibb_cache__[x] = fibb(x-1) + fibb(x-2)
    return __fibb_cache__[x]

def f(i, j):
    return fibb(i) + fibb(j)

def circle(i, j):
    return int(int(sqrt(i**2 + j**2)) == 50)

def f(i, j):
    return circle(i, j)

def image(x, y):
    pixels = np.zeros((x, y))
    for i in range(x):
        for j in range(y):
            pixels[i, j] = f(i, j)
    print(pixels)
    return pixels

N = 50
plt.imshow(image(N, N))
plt.show()
