#!/usr/bin/env python3
from methods.legacy.brute_force import brute_force
from methods.legacy.heuristic   import heuristic
from methods.tree import tree
from methods.arithmetic import operators
#from methods.generate import generate

def main():
    #for item in generate():
    #    print(item)
    #1/0
    #print(operators)
    N = 10
    a = 3
    def function(x): 
        return 1 if x == 1 else a + function(x-1)
    def function(x):
        if x == 1:
            return 1
        elif x == 2:
            return 1
        else:
            return function(x-1) + function(x-2)
    #def function(x): 
    #    return 2 if x == 1 else 3 * function(x-1)
    inputs  = list(range(1, N+1))
    outputs = list(map(function, inputs))

    tree(inputs, outputs, depth=3)

if __name__ == '__main__':
    main()
