#!/usr/bin/env python3
import sys

import matplotlib.pyplot as plt
import numpy as np

ax, bx = -2.5, 1.0
ay, by = -1.0, 1.0
max_iterations = 100

def mandelbrot(i, j, N):
    x0 = (i/N)*(bx - ax) + ax # Scale
    y0 = (j/N)*(by - ay) + ay # Scale
    x = 0
    y = 0
    iteration = 0
    while x**2 + y**2 < 2**2 and iteration < max_iterations:
        xtemp = x**2 - y**2 + x0
        y = 2*x*y + y0
        x = xtemp
        iteration += 1
    return iteration

def main(args):
    N = 500
    M = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            M[i, j] = mandelbrot(i, j, N)
    #1/0
    print(M)
    plt.imshow(M, cmap='magma')
    plt.show()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
